### ISSUE TITLE
win_list.c compile issue

### ISSUE THREAD

**Issue by RichardWadeBrooks** [codeplea/Hands-On-Network-Programming-with-C#11]
[error.log](https://github.com/codeplea/Hands-On-Network-Programming-with-C/files/6154439/error.log)

**Comment by RichardWadeBrooks** [comment]
I got compile errors with win_list.c file I downloaded.

**Comment by codeplea** [comment]
What version of Windows are you using?

Can you try adding this to the top of the file:

```
#include <winerror.h>
```

This shouldn't be needed, but I think it might fix your issue.

The documentation for `GetAdaptersInfo()` is at https://docs.microsoft.com/en-us/windows/win32/api/iphlpapi/nf-iphlpapi-getadaptersinfo It looks like including only "iphlpapi.h" should be enough.

I'm not exactly sure why you would get this error. Are you able to compile and run other Windows programs - not just command-line programs, but programs using different Windows APIs?

**Comment by RichardWadeBrooks** [comment]
I am running Windows 10 Home operating system Version 2004 OS Build 19041.867.   I added the include and that fixed it.   Thanks.   Now to figure out how to convince McAfee it is not a virus (add it to the do not scan list).
