### ISSUE TITLE
ssh_download failed on Windows 10

### ISSUE THREAD

**Issue by BeneficialCode** [codeplea/Hands-On-Network-Programming-with-C#13]
when I run the "ssh_download.exe localhost 22 username" command in cmd.exe, I try to download the test.txt that I have created in advance. But ssh_scp_pull_request() failed. Then I try to use the absolute path, it still failed. I promise that the test.txt is existing in that path.
![bug](https://user-images.githubusercontent.com/40847073/121836415-f2fb0600-cd05-11eb-8a5b-ec90f978d13f.png)
![bug1](https://user-images.githubusercontent.com/40847073/121836421-f68e8d00-cd05-11eb-8989-de9c3231e288.png)
![bug2](https://user-images.githubusercontent.com/40847073/121836426-f8585080-cd05-11eb-868d-eaaf6379b496.png)
I don't know the reason.

**Comment by codeplea** [comment]
In your screenshot, where is the text "Remote command to execute" coming from? Did you modify the program? After the chdir, can you make it list the directory's contents?

Are you sure you have permissions on the file your are requesting? Are you able to successfully download your test file using another program, such as WinSCP?

**Comment by BeneficialCode** [comment]
I modify the ssh_auth.c. Add the ssh_command.c's code in it. I can run the remote command success, such as dir, chdir. ipconfig 

etc.

WinSCP use the fSFTP protocol is successfully connect. However, use the SCP protocol is failed. 

![success](https://user-images.githubusercontent.com/40847073/121843680-4de82980-cd15-11eb-8ef8-e23977ef2ac1.png)

![failed](https://user-images.githubusercontent.com/40847073/121843202-673ca600-cd14-11eb-9f99-a0ff541ea0d4.png)

![failed2](https://user-images.githubusercontent.com/40847073/121843317-96ebae00-cd14-11eb-9b21-bb3aac29b367.png)

**Comment by codeplea** [comment]
When you run the dir command over ssh, what does it return?

**Comment by codeplea** [comment]
If WinSCP cannot download the file over SCP, then it seems that the issue is with your server configuration.

**Comment by BeneficialCode** [comment]
I use the default configuration. I don't know how to configuration the sshd_configure. (path: C:\ProgramData\ssh). 
when I run dir, it return the directory.

**Comment by codeplea** [comment]
I have not worked with OpenSSH server on Windows, but this makes it appear that SCP must be specifically enabled: https://www.georgiasoftworks.com/ssh-server-windows/faq/how-to-enable-ssh-scp

**Comment by BeneficialCode** [comment]
This registry key is not existing on my local system.
