### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by ghenry** [codeplea/Hands-On-Network-Programming-with-C#15]
Just recently started my own open source project called SentryPeer and thanks to your book and example code I have my first UDP server for the project:

https://github.com/SentryPeer/SentryPeer/blob/main/src/sip_daemon.c

Thanks for writing it!

**Comment by codeplea** [comment]
Awesome! I'm glad you're finding the book useful, and thanks for taking the time to comment.

That actually looks like a really cool project too! Great idea sharing honeypot attackers peer-to-peer like this.

**Comment by ghenry** [comment]
Thanks! Hopefully I’ll make it.
