### ISSUE TITLE
Closing socket_listen if it socket returns < 0

### ISSUE THREAD

**Issue by ghenry** [codeplea/Hands-On-Network-Programming-with-C#16]
Hi Lewis,

I'm running the UDP server code through [Coverity](https://scan.coverity.com/projects/sentrypeer-sentrypeer) analysis and it states then returning here:

https://github.com/codeplea/Hands-On-Network-Programming-with-C/blob/cc67208a65a3ef577050f18fc35d7579bbbe89bb/chap04/udp_serve_toupper.c#L54

means socket_listen leaks resources when it goes out of scope. If you try to `CLOSESOCKET(socket_listen);` there, then it complains (rightly so) that:

```
54      if (!ISVALIDSOCKET(socket_listen)) {
55        fprintf(stderr, "socket() failed. (%d)\n", GETSOCKETERRNO());
>>>     CID 364052:  Error handling issues  (NEGATIVE_RETURNS)
>>>     "socket_listen" is passed to a parameter that cannot be negative.
           return 1;
```

what is the recommended technique here to handle that?

**Comment by ghenry** [comment]
Sorry, clicked submit by mistake. See my edits above.

**Comment by codeplea** [comment]
I'm not sure I follow. If `!ISVALIDSOCKET(...)` is true, then there is no need to call close on the socket, as it wasn't properly opened in the first place. i.e. it's not leaking resources.

However, in that example program, almost every _other_ place you see `return 1;` it would leak resources if the program didn't immediately terminate. This was simply done to shorten the example programs. In a real-world program that wouldn't immediately terminate on this type of exception, then you would need to properly clean-up the allocated resources.

**Comment by ghenry** [comment]
Thanks Lewis. I've removed that close and will see what it says and report back.

**Comment by ghenry** [comment]
That has cleared the issue - https://scan.coverity.com/projects/sentrypeer-sentrypeer

Thanks!
