### ISSUE TITLE
The # will never be removed when parsing the path. 

### ISSUE THREAD

**Issue by stevethibault** [codeplea/Hands-On-Network-Programming-with-C#18]
https://github.com/codeplea/Hands-On-Network-Programming-with-C/blob/cc67208a65a3ef577050f18fc35d7579bbbe89bb/chap06/web_get.c#L67

Shouldn't this be *p++, since you are checking if *p == 0 in the look directly below which will always be true since we're setting *p = 0 here, and the loop looking for the hash will never be executed as the while condition is satisfied already? I don' think the # will ever be found and nulled out of the path and therefore is sent to the server with the current code.

**Comment by codeplea** [comment]
You are correct. Thanks!
