### ISSUE TITLE
Some errors with OpenSSL on macOS High Sierra

### ISSUE THREAD

**Issue by proyb6** [codeplea/Hands-On-Network-Programming-with-C#2]
I couldn't successfully compile with various errors on OpenSSL using 1.0.2s installed from brew.

https://github.com/codeplea/Hands-On-Network-Programming-with-C/blob/e785d5389bad5fd4946a3f40de674fc6570b8173/chap09/openssl_version.c#L29

The working code
```
printf("OpenSSL version: %s\n", SSLeay_version(SSLEAY_VERSION));
```

**Comment by codeplea** [comment]
The code is not designed to support your OpenSSL version, but if you read the book it would help you out a lot. This change is mentioned specifically in the book. Here's an except:

![openssl](https://user-images.githubusercontent.com/14815717/64538060-93c2c300-d2e1-11e9-99c8-9a3e21ee6c0c.PNG)
