### ISSUE TITLE
TLS_server_method error

### ISSUE THREAD

**Issue by proyb6** [codeplea/Hands-On-Network-Programming-with-C#3]
Have compiled with OpenSSL 1.0.2s result in error, replaced with the sample code from OpenSSL site.

https://github.com/codeplea/Hands-On-Network-Programming-with-C/blob/e785d5389bad5fd4946a3f40de674fc6570b8173/chap10/https_server.c#L288

Replace with working code:
```
SSL_CTX *ctx = SSL_CTX_new(SSLv23_server_method());
```

https://wiki.openssl.org/index.php/Simple_TLS_Server

**Comment by codeplea** [comment]
You should really use a newer version of OpenSSL.

Also, this code is designed to accompany the book. The book would have saved you a lot of hassle. Here's a small except from the book regarding this issue.

![chap10](https://user-images.githubusercontent.com/14815717/64537785-1b5c0200-d2e1-11e9-951f-9e50809e4c91.png)
