### ISSUE TITLE
Testing STMP with port 25

### ISSUE THREAD

**Issue by cmcknight** [codeplea/Hands-On-Network-Programming-with-C#7]
I'm working through the SMTP code (chapter 8) under Ubuntu and I wanted to share a tip for folks who cannot use port 25 for whatever reason. Under Linux and MacOS you can set up a local mail server to test against. I found a gist on Github [link](https://gist.github.com/raelgc/6031274) that has step-by-step instructions for doing so. Not sure about Windows as I haven't worked in that OS for a long time.

**Comment by codeplea** [comment]
Thanks for the tip.
